### PR TITLE
New feature: Get and count method for db and file storage and its tests

### PR DESCRIPTION
**Pull request by FoleKhali**
Hi, I'm adding this changes to the mentioned files and I'm want to know what you think about them!
+ Adding get and count method for db storage and file storage.
+ Adding tests for db storage and file storage.
+ Fixing tests for amenity and base model classes.

### CODE REVIEW

**Comment by luismch158158** [comment]
Hi Dhanna, I loved how you implemented the get and count method in DBStorage and File Storage. Good Work!

**Comment by luismch158158** [comment]
Please fix this whitespace after this word in AUTHOR file
image

**Comment by FoleKhali** [comment]
I've already fix the problem! Thanks for seeing my changes and review it.

**Comment by luismch158158** [comment]
Great, thank you.
That's all.

**Pull request merged**
